# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://microwidgets.dev" # Your main domain
baseurl: "/blog" # The subpath of your site
title: MicroWidgets Blog
description: >-
  One-click website upgrades for developers who'd rather code. Auto-update GitHub activity, customer counts, and status info. No redeploys. Save time.
logo: "/assets/images/logo.png"
twitter_username: marcos_placona
github_username: mplacona
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/London" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: "MicroWidgets"
  avatar: "/assets/images/icon.png"
  bio: "One-click HTML Widgets for developers who'd rather code than configure"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://MicroWidgets.dev"
    - label: "Twitter"
      icon: "fab fa-brands fa-x-twitter"
      url: "https://twitter.com/marcos_placona"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mplacona"

footer:
  links:
    - label: "Twitter"
      icon: "fa-brands fa-x-twitter"
      url: "https://twitter.com/marcos_placona"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mplacona"

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      image: /assets/images/widgets.jpg
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
